# Generated by Django 4.2.6 on 2023-11-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherinwallet',
            name='used_at',
        ),
        migrations.AddField(
            model_name='voucherinwallet',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
